### ISSUE TITLE
Need help in understanding internals

### ISSUE THREAD

**Issue by notsuretho** [reinhrst/fzf-lib#1]
Hey! Great to see an effort being made to make FZF usable for general purpose. I wish I had learnt Go so I could work on it myself. 

I too was going through jungunn's fzf codebase though I couldn't understand it completely. I know this is big of an ask, but could you help me understand few parts on why they are there and how they are being used?

- I've seen [chunklist being created](https://github.com/reinhrst/fzf-lib/blob/main/core.go#L75-L80) and consumed at many parts of the code.  What does a chunklist do, and how are they used?
- I believe FZF runs a query against a text and we get back a result. I want to know how FZF is sorting these results, is it filling these results in a priority queue or doing something else?
- [In the blog](https://blog.claude.nl/tech/making-fzf-into-a-golang-library-fzf-lib/) you mentioned FZF caches intermediate results. Does it mean that the results for a query, say "som", can be be used for subsequent query "some"? If yes, could you please point me to the code in junegunn's fzf where this is done?

PS: Not sure, but ["cannel" here](https://github.com/reinhrst/fzf-lib/blob/7fe21dbf5365b974b2b91f3f22a46d9b8949e130/core.go#L123) could be a typo and maybe needs to be "channel".

**Comment by reinhrst** [comment]
Hi,

Let's start with the last issue (the easiest :)); yeah Cannel was a typo (and thanks to auto code completion I never noticed....), fixed now in v0.9.0, thanks! :)

As for the rest:

# Chunklist

So, I cannot say that I fully understand all the code; I just stripped the parts that I thought were not necessary and then kept removing stuff until my tests started to fail :|. However, if I remember and understand correctly, a chunklist is a bunch of "hay" to search through (so a bunch of lines in your code you're searching through). Splitting things up means that multiple chunks can be handed to multiple processors, as well as allowing some housekeeping code between chunks. e.g. after finishing a chunk (if 200ms has passed since the start), the progress indicator (percentage) is updated (try searching through the linux source code or something else with millions of lines), you will see a percentage of search completed. This is updated between chunks. Also if a new search starts before the current search has finished, between chunks the system checks whether it should continue on the current search or start a new one.
Possibly within the original fzf they also have a job to incrementally search while new lines come in (i.e. there is some cache on the chunks, so maybe only the last chunk that gets appended to needs to be searched again), however I have even less of a view on that.

# Sorting
Not entirely sure what you mean. There is an original location, a score for each hit, a match begin location, and match length. You can decide on which to sort. Or do you mean the exact code location where the sort is done (in which case, just look for sort.Sort). Or how the score is determined? You can read some stuff in algo.go, although I don't think this is the whole story.

# Cache
It's a bit the same as my first response; I don't know all the ins and outs. I did get bitten at some points when I removed too much code, and accidentally removed some cache invalidation.
I don't know exactly if "som" can be used to speed up "some" (it may or may not be worth it), but I do *believe* that if you searched for "apple" it will speed up "apple pear".

I would start looking in [cache.go](https://github.com/junegunn/fzf/blob/764316a53d0eb60b315f0bbcd513de58ed57a876/src/cache.go), and work forward from there.

**Comment by notsuretho** [comment]
Thank you! That explanation on chunklist has cleared quite a lot of things for me.

Yes I was looking for the way how sorting is done, which as you mentioned is plain `sort.Sort` with no special data structures applied.  One thing that I'm still not able to understand though, now that we have a list of partial results where each [partial result is itself sorted](https://github.com/reinhrst/fzf-lib/blob/65ba3a85aa55ff1e0467f8f7ab4bca6bac47a7a9/matcher.go#L190-L197), where are we merging these results and re-sorting them? What I mean is that [here we'll have items](https://github.com/reinhrst/fzf-lib/blob/65ba3a85aa55ff1e0467f8f7ab4bca6bac47a7a9/matcher.go#L226)  with scores like

```json
[ [ 74, 32, 16 ], [ 79, 12, 2 ] ]
```

Now directly appending to the resultant list [like we did here](https://github.com/reinhrst/fzf-lib/blob/65ba3a85aa55ff1e0467f8f7ab4bca6bac47a7a9/core_test.go#L22) will give us

```json
[ 74, 32, 16, 79, 12, 2 ]
```

and not 

```json
[ 79, 74, 32, 16, 12, 2 ]
```

I couldn't find the code where these subarrays were flattened in a list and were sorted again. Maybe I missed something?

**Comment by reinhrst** [comment]
Ah, I understand. I had a quick look in the code, looks to me that this happens only on the merger.Get(). This calls [mergedGet in merged.go](https://github.com/reinhrst/fzf-lib/blob/65ba3a85aa55ff1e0467f8f7ab4bca6bac47a7a9/merger.go#L96), which sorts while merging, on the fly up until the index that you're trying to  get (while caching whatever has been merged).

**Comment by notsuretho** [comment]
Yeah, that sums up. Thanks!

**Comment by i2** [comment]
It is worth adding this detailed explanation to the main readme of the repo. Sorry to revive a closed issue but thought it'd be useful for others!

**Comment by reinhrst** [comment]
I'll at least put in a link, thanks for the suggestion!
